import type { ReactNode } from 'react';

import { Inter } from 'next/font/google';
import { getServerSession } from 'next-auth/next';

import Provider from '@/src/app/context/client-provider';
import { options } from './api/auth/[...nextauth]/options';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	description: 'Generated by create next app',
	title: 'NextAuth Demo',
};


async function RootLayout({ children }: { children: ReactNode }) {
	const session = await getServerSession(options);
	return (
		<html lang="en">
			<body className={`${inter.className} min-h-screen bg-gray-100`}>
				<Provider session={session}>{children}</Provider>
			</body>
		</html>
	);
}

export default RootLayout;
