import type { ReactNode } from 'react';

import type { Session } from 'next-auth';
import { Inter } from 'next/font/google';

import Provider from '@/src/app/context/client-provider';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	description: 'Generated by create next app',
	title: 'NextAuth Demo',
};

interface RootLayoutProps {
	children: ReactNode;
	session: Session | null;
}

function RootLayout({ children, session }: RootLayoutProps) {
	return (
		<html lang="en">
			<body className={`${inter.className} min-h-screen bg-gray-100`}>
				<Provider session={session}>{children}</Provider>
			</body>
		</html>
	);
}

export default RootLayout;
